config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/health-check" => "health_check#show"

  namespace :notification do
    resources :wastes
    resources :devices do
      collection do
        delete "remove" => "devices#destroy"
        post "send_notifications" => "devices#send_notifications"
        post "send_notification/:id" => "devices#send_notification", as: :send_notification
      end
    end
    post "push_device_assignments/add" => "push_device_assignments#add", defaults: { format: "json" }
    delete "push_device_assignments/remove" => "push_device_assignments#remove", defaults: { format: "json" }
  end
  resources :categories
  resources :app_user_contents
  resources :static_contents
  resources :media_contents, only: %i[create], defaults: { format: "json" }
  get "data_provider", to: "data_provider#show", as: :data_provider
  get "data_provider/edit", as: :edit_data_provider
  post "data_provider/update", as: :update_data_provider
  resources :accounts do
    member do
      get "batch_defaults"
    end
  end

  get "/waste_calendar/export", to: "notification/wastes#ical_export", defaults: { format: "ics" }

  get "confirmation/error", to: "public/confirm_records#error"
  get "confirmation/:confirm_action/:token", to: "public/confirm_records#confirm", as: :confirm_record_action
  delete "confirmation/destroy/:token", to: "public/confirm_records#destroy"

  use_doorkeeper do
    controllers applications: "oauth/applications"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get "user" => "users/status#show"

  authenticate :user do
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    match "/background" => BetterDelayedJobWeb, anchor: false, via: [:get, :post]
  end

  post "/graphql", to: "graphql#execute"

  get "/generate_204", to: "application#generate_204", status: 204

  get "*not_found", to: "application#not_found_404", status: 404

  root to: redirect("accounts")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
# frozen_string_literal: true

module Notification
  def self.table_name_prefix
    "notification_"
  end
end

app/models/notification/device.rb
# frozen_string_literal: true

class Notification::Device < ApplicationRecord
  enum device_type: { undefined: 0, ios: 1, android: 2 }
  has_many :waste_registrations,
           class_name: "Waste::DeviceRegistration",
           primary_key: "token",
           foreign_key: "notification_device_token"
  has_many :notification_push_device_assignments,
           class_name: "Notification::PushDeviceAssignment",
           foreign_key: "notification_device_id",
           dependent: :destroy
  has_many :pushes,
           through: :notification_push_device_assignments,
           class_name: "Notification::Push",
           source: :notification_push

  serialize :exclude_data_provider_ids, Array
  serialize :exclude_mowas_regional_keys, Array

  include Sortable
  sortable_on :device_type, :token

  include Searchable
  searchable_on :token

  # Zusätzlich zu der Validierung hier existiert auch ein unique Index auf das Feld 'token'
  validates_uniqueness_of :token, on: :create, message: "must be unique"
  validates_presence_of :token, on: :create, message: "can't be blank"
end

# == Schema Information
#
# Table name: notification_devices
#
#  id                          :bigint           not null, primary key
#  token                       :string(255)
#  device_type                 :integer          default("undefined")
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  exclude_data_provider_ids   :text(65535)
#  exclude_mowas_regional_keys :text(65535)
#

app/models/notification/push_device_assignment.rb
# frozen_string_literal: true

class Notification::PushDeviceAssignment < ApplicationRecord
  belongs_to :notification_push, class_name: "Notification::Push"
  belongs_to :notification_device, class_name: "Notification::Device"

  validates_presence_of :notification_push
  validates_presence_of :notification_device
  validates_uniqueness_of :notification_push, scope: :notification_device
end

# == Schema Information
#
# Table name: notification_push_device_assignments
#
#  id                     :bigint           not null, primary key
#  notification_push_id   :integer
#  notification_device_id :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/controllers/notification/devices_controller.rb
# frozen_string_literal: true

class Notification::DevicesController < ApplicationController
  layout "doorkeeper/admin"

  include SortableController

  skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]

  before_action :auth_user_or_doorkeeper, only: [:create, :update, :destroy]
  before_action :authenticate_user!, except: [:create, :update, :destroy]
  before_action :authenticate_admin, except: [:create, :update, :destroy]
  before_action :set_notification_device, only: [:show, :edit, :update, :destroy, :send_notification]

  def authenticate_admin
    render inline: "not allowed", status: 405 unless current_user.admin_role?
  end

  def auth_user_or_doorkeeper
    raise "unauthorized" if current_user.present? && !current_user.admin_role?

    doorkeeper_authorize! if current_user.blank?
  end

  def send_notifications
    options = params.permit![:notification]
    PushNotification.delay.send_notifications(options) if options[:title].present?

    respond_to do |format|
      format.html { redirect_to notification_devices_url, notice: "Push Notifications gesendet" }
    end
  end

  def send_notification
    options = params.permit![:notification]
    PushNotification.delay.send_notification(@notification_device, options) if options[:title].present?

    respond_to do |format|
      format.html { redirect_to notification_device_path(@notification_device), notice: "Push Notification gesendet" }
    end
  end

  # GET /notification/devices
  # GET /notification/devices.json
  def index
    @notification_devices = Notification::Device
      .sorted_for_params(params)
      .where_token_contains(params[:query])
      .page(params[:page])

    @push_logs = RedisAdapter.get_push_logs
  end

  # GET /notification/devices/1
  # GET /notification/devices/1.json
  def show
    @push_logs = RedisAdapter.get_push_logs_for_device(@notification_device.token)
  end

  # GET /notification/devices/new
  def new
    @notification_device = Notification::Device.new
  end

  # GET /notification/devices/1/edit
  def edit
    @push_logs = RedisAdapter.get_push_logs_for_device(@notification_device.token)
  end

  # POST /notification/devices
  # POST /notification/devices.json
  def create
    @notification_device = Notification::Device.new(notification_device_params)

    respond_to do |format|
      begin
        if @notification_device.save
          format.html { redirect_to @notification_device, notice: "Device was successfully created." }
          format.json { render :show, status: :created, location: @notification_device }
        else
          format.html { render :new }
          format.json { render json: @notification_device.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordNotUnique
        format.html { render :new }
        format.json { render json: @notification_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notification/devices/1
  # PATCH/PUT /notification/devices/1.json
  def update
    respond_to do |format|
      if @notification_device.present? && @notification_device.update(notification_device_params)
        format.html { redirect_to @notification_device, notice: "Device was successfully updated." }
        format.json { render :show, status: :ok, location: @notification_device }
      else
        format.html { render :edit }
        format.json { render json: @notification_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notification/devices/1
  # DELETE /notification/devices/1.json
  def destroy
    respond_to do |format|
      if @notification_device.present?
        Notification::Device.where(token: @notification_device.token).destroy_all
        format.html { redirect_to notification_devices_url, notice: "Device was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to notification_devices_url, notice: "Device was successfully destroyed." }
        format.json { render json: nil, status: 404 }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_notification_device
      token = notification_device_params[:token] if params[:notification_device].present?
      @notification_device = Notification::Device.find_by(token: token) and return if token.present?
      @notification_device = Notification::Device.find(params[:id]) if params[:id].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_device_params
      params.require(:notification_device).permit(
        :token, :device_type, exclude_data_provider_ids: [], exclude_mowas_regional_keys: []
      )
    end
end

app/controllers/notification/push_device_assignments_controller.rb
# frozen_string_literal: true

class Notification::PushDeviceAssignmentsController < ApplicationController
  layout "doorkeeper/admin"

  skip_before_action :verify_authenticity_token

  before_action :auth_user_or_doorkeeper
  before_action :set_notification_device
  before_action :set_notification_pushes

  def auth_user_or_doorkeeper
    raise "unauthorized" if current_user.present? && !current_user.admin_role?

    doorkeeper_authorize! if current_user.blank?
  end

  # POST /notification/push_device_assignments/add.json
  def add
    @notification_pushes.each do |notification_push|
      Notification::PushDeviceAssignment.create(
        notification_push: notification_push,
        notification_device: @notification_device
      )
    end

    respond_to do |format|
      format.json { head :no_content }
    end
  rescue StandardError
    respond_to do |format|
      format.json { render json: {}, status: :unprocessable_entity }
    end
  end

  # DELETE /notification/push_device_assignments/remove.json
  def remove
    @notification_pushes.each do |notification_push|
      Notification::PushDeviceAssignment.where(
        notification_push: notification_push,
        notification_device: @notification_device
      ).destroy_all
    end

    respond_to do |format|
      format.json { head :no_content }
    end
  rescue StandardError
    respond_to do |format|
      format.json { render json: {}, status: :unprocessable_entity }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_notification_device
      token = push_device_assignment_params[:token]
      @notification_device = Notification::Device.find_by(token: token) if token.present?
    end

    def set_notification_pushes
      notification_pushable_id = push_device_assignment_params[:notification_pushable_id]
      notification_pushable_type = push_device_assignment_params[:notification_pushable_type]
      @notification_pushes = []

      if notification_pushable_id.present? && notification_pushable_type.present?
        @notification_pushes = Notification::Push.where(
          notification_pushable_id: notification_pushable_id,
          notification_pushable_type: notification_pushable_type
        )
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def push_device_assignment_params
      params.require(:notification_push_device_assignment).permit(
        :token, :notification_pushable_id, :notification_pushable_type
      )
    end
end

app/controllers/notification/wastes_controller.rb
# frozen_string_literal: true

class Notification::WastesController < ApplicationController
  layout "doorkeeper/admin"

  skip_before_action :verify_authenticity_token, only: [:create, :destroy]
  before_action :auth_user_or_doorkeeper, only: [:index, :create, :destroy]

  def auth_user_or_doorkeeper
    raise "unauthorized" if current_user.present? && (!current_user.admin_role? || !current_user.app_role?)

    doorkeeper_authorize! if current_user.blank?
  end

  # GET /notification/wastes
  # GET /notification/wastes.json
  def index
    @notification_device = Notification::Device.find_by(token: params[:token])
    @waste_device_registrations = @notification_device.waste_registrations if @notification_device.present?

    respond_to do |format|
      if @waste_device_registrations.present?
        format.json { render json: @waste_device_registrations }
      else
        format.json { render json: [] }
      end
    end
  end

  # POST /notification/wastes
  # POST /notification/wastes.json
  def create
    @notification_device = Notification::Device
                             .where(token: notification_device_params[:token])
                             .first_or_create(device_type: notification_device_params[:device_type])

    if @notification_device.present?
      @waste_device_registration = Waste::DeviceRegistration
                                     .where(waste_registration_params.merge(notification_device_token: @notification_device.token))
                                     .first_or_create
      @waste_device_registration.update(waste_registration_update_params)
    end

    respond_to do |format|
      format.json {
        render json: @waste_device_registration.to_json(
          only: [:id, :street, :zip, :city, :created_at, :updated_at, :notify_days_before, :notify_for_waste_type],
          methods: [:notify_at_time]
          ), status: :created
      }
    end
  end

  # DELETE /notification/wastes/1
  # DELETE /notification/wastes/1.json
  def destroy
    @notification_device = Notification::Device.find_by(token: params[:token])
    @waste_device_registration = @notification_device.waste_registrations.where(id: params[:id]).first

    respond_to do |format|
      if @waste_device_registration.present?
        @waste_device_registration.destroy
        format.json { render json: @waste_device_registration, status: 202 }
      else
        format.json { render json: {}, status: 404 }
      end
    end
  end

  def ical_export
    address_search_params = ical_export_params.slice(:street, :city, :zip).delete_if { |_key, value| value.blank? }
    address = Address.joins(:waste_location_types).where(address_search_params).first
    raise "Address not found" if address.blank?

    zip_and_city = [address.zip, address.city].compact.delete_if(&:blank?).join(" ")
    full_address = [address.street, zip_and_city].compact.delete_if(&:blank?).join(", ")

    waste_types = StaticContent.find_by(name: "wasteTypes").try(:content)
    waste_types = JSON.parse(waste_types) if waste_types.present?
    return if waste_types.blank?

    @cal = Icalendar::Calendar.new
    @cal.append_custom_property("NAME", "Abfallkalender")
    @cal.append_custom_property("X-WR-CALNAME", "Abfallkalender")
    @cal.append_custom_property("DESCRIPTION", "Alle Abholtermine der Müllabfuhr für #{full_address}")
    @cal.append_custom_property("X-WR-CALDESC", "Alle Abholtermine der Müllabfuhr für #{full_address}")
    address.waste_location_types.each do |waste_location_type|
      waste_label = waste_types.dig(waste_location_type.waste_type, "label")
      waste_location_type.pick_up_times.each do |pick_up_time|
        formated_pickup_start_date_for_time = Icalendar::Values::Date.new(pick_up_time.pickup_date.strftime("%Y%m%d"))
        formated_pickup_end_date_for_time = Icalendar::Values::Date.new((pick_up_time.pickup_date + 1.day).strftime("%Y%m%d"))

        event = Icalendar::Event.new
        event.dtstart = formated_pickup_start_date_for_time
        event.dtend = formated_pickup_end_date_for_time
        event.summary = ["Abfallkalender", waste_label].join(": ")
        event.description = "Abholung #{waste_label} in #{ical_export_params[:street]}"
        event.location = full_address

        @cal.add_event(event)
      end
    end
    @cal.publish

    respond_to do |format|
      format.ics
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_device_params
      params.require(:notification_device).permit(:token, :device_type)
    end

    def waste_registration_params
      params.require(:waste_registration).permit(:street, :city, :zip, :notify_for_waste_type)
    end

    def ical_export_params
      params.permit(:street, :city, :zip, :format)
    end

    def waste_registration_update_params
      params.require(:waste_registration).permit(:notify_days_before, :notify_at)
    end
end

app/views/notification/devices/_form.html.erb
<%= form_with(model: notification_device, local: true) do |form| %>
  <% if notification_device.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(notification_device.errors.count, "error") %>
        prohibited this notification_device from being saved:
      </h2>

      <ul>
      <% notification_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :token %>
    <%= form.text_field :token, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :device_type, "Operating system" %>
    <%= form.select :device_type, Notification::Device.device_types.keys, {} , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit t("doorkeeper.applications.buttons.submit"), class: "btn btn-primary" %>
    <%= link_to t("doorkeeper.applications.buttons.cancel"), notification_devices_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/notification/devices/_push_logs.html.erb
<h1>Push Notifications Logs</h1>
<p>Alte Daten werden automatisch gelöscht</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Messages Title</th>
      <th>Messages Body</th>
      <th>Messages Data</th>
      <th>Payload</th>
    </tr>
  </thead>
  <tbody>
    <% @push_logs.each do |message| %>
      <% serialized_message = JSON.parse(message) rescue {} %>
      <tr>
        <td><%= serialized_message["date"] %></td>
        <td><%= serialized_message["title"] %></td>
        <td><%= serialized_message["body"] %></td>
        <td><%= serialized_message["data"] %></td>
        <td><%= serialized_message["payload"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notification/devices/_send_notification.html.erb
<% submit_path ||= send_notification_notification_devices_path(@notification_device) %>
<% submit_text ||= "An Device senden" %>
<% data_resources_for_select = DataResourceSetting::DATA_RESOURCES.map(&:to_s).sort %>
<% data_providers_for_select = DataProvider.all.map { |dp| [dp.name, dp.id] }
                                               .sort_by { |dp| dp[0].downcase } %>

<%= form_tag(submit_path, method: :post) do  %>
  <div class="form-group">
    <%= label_tag "notification_title", "Title *" %>
    <%= text_field_tag "notification[title]", nil ,class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= label_tag "notification_body", "Body" %>
    <%= text_field_tag "notification[body]", nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "notification_data_query_type", "Data type" %>
    <%= select_tag "notification[data][query_type]",
                   options_for_select(data_resources_for_select),
                   class: "form-control",
                   include_blank: true %>
  </div>

  <div class="form-group">
    <%= label_tag "notification_data_id", "Data ID" %>
    <%= text_field_tag "notification[data][id]", nil, class: "form-control" %>
    <small class="form-text text-muted">
      Hier kann die ID eines bestimmten Datensatzes mitgegeben werden
    </small>
  </div>

  <div class="form-group">
    <%= label_tag "notification_data_data_provider_id", "Data Provider ID" %>
    <%= select_tag "notification[data][data_provider_id]",
                   options_for_select(data_providers_for_select),
                   class: "form-control",
                   include_blank: true %>
    <small class="form-text text-muted">
      Hier kann die ID eines bestimmten Data Providers mitgegeben werden
    </small>
  </div>

  <div class="form-group">
    <%= submit_tag submit_text, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notification/devices/edit.html.erb
<div class="row">
  <div class="col">
    <h1>Device bearbeiten</h1>

    <%= render "form", notification_device: @notification_device %>
  </div>
</div>

app/views/notification/devices/index.html.erb
<div class="row">
  <div class="col">
    <h1>Push Notifications senden</h1>

    <%= render(
          partial: "notification/devices/send_notification",
          locals: {
            submit_path: send_notifications_notification_devices_path,
            submit_text: "An #{pluralize(@notification_devices.total_count, "Device")} senden"
          }
        ) %>

    <br />

    <h1 id="devices">Devices</h1>

    <p><%= link_to 'New Device', new_notification_device_path, class: "btn btn-success" %></p>

    <%= render partial: 'search_form', locals: { form_path: notification_devices_path, search_column: 'token' } %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            <%= link_to "Token", notification_devices_path(params_for_link(:token)) + "#devices" %>
            <%= render partial: 'sort_icon', locals: { sort_column: 'token' } %>
          </th>
          <th>
            <%= link_to "Operating System", notification_devices_path(params_for_link(:device_type)) + "#devices" %>
            <%= render partial: 'sort_icon', locals: { sort_column: 'device_type' } %>
          </th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @notification_devices.each do |notification_device| %>
          <tr>
            <td class="align-middle"><%= notification_device.token %></td>
            <td class="align-middle"><%= notification_device.device_type %></td>
            <td class="align-middle" style="width: 70px"><%= link_to 'More', notification_device_path(notification_device), class: 'btn btn-sm btn-outline-secondary' %></td>
            <td class="align-middle" style="width: 70px"><%= link_to 'Destroy', notification_device, method: :delete,class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @notification_devices, theme: 'twitter-bootstrap-4' %>

    <br />

    <h1>All Push Notifications Logs</h1>
    <p>Alte Daten werden automatisch gelöscht</p>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Device Token</th>
          <th>Messages Title</th>
          <th>Messages Body</th>
          <th>Messages Data</th>
          <th>Payload</th>
        </tr>
      </thead>
      <tbody>
        <% @push_logs.each do |token, messages| %>
          <% messages.each do |message| %>
            <% serialized_message = JSON.parse(message) rescue {} %>
            <tr>
              <td><%= serialized_message["date"] %></td>
              <td><%= token %></td>
              <td><%= serialized_message["title"] %></td>
              <td><%= serialized_message["body"] %></td>
              <td><%= serialized_message["data"] %></td>
              <td><%= serialized_message["payload"] %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/notification/devices/new.html.erb
<div class="row">
  <div class="col">
    <h1>Device anlegen</h1>

    <%= render "form", notification_device: @notification_device %>
  </div>
</div>

app/views/notification/devices/show.html.erb
<div class="row">
  <div class="col">
    <h1>Device</h1>

    <div class="form-group">
      <label>Token</label>
      <div><code><%= @notification_device.token %></code></div>
    </div>

    <div class="form-group">
      <label>Device type</label>
      <div><code><%= @notification_device.device_type %></code></div>
    </div>

    <div class="form-group">
      <%= link_to t("doorkeeper.applications.buttons.back"), notification_devices_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

<br />

<h1>Push Notification senden</h1>

<%= render partial: "notification/devices/send_notification" %>

<br />

<%= render partial: "notification/devices/push_logs" %>