config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/health-check" => "health_check#show"

  namespace :notification do
    resources :wastes
    resources :devices do
      collection do
        delete "remove" => "devices#destroy"
        post "send_notifications" => "devices#send_notifications"
        post "send_notification/:id" => "devices#send_notification", as: :send_notification
      end
    end
    post "push_device_assignments/add" => "push_device_assignments#add", defaults: { format: "json" }
    delete "push_device_assignments/remove" => "push_device_assignments#remove", defaults: { format: "json" }
  end
  resources :categories
  resources :app_user_contents
  resources :static_contents
  resources :media_contents, only: %i[create], defaults: { format: "json" }
  get "data_provider", to: "data_provider#show", as: :data_provider
  get "data_provider/edit", as: :edit_data_provider
  post "data_provider/update", as: :update_data_provider
  resources :accounts do
    member do
      get "batch_defaults"
    end
  end

  get "/waste_calendar/export", to: "notification/wastes#ical_export", defaults: { format: "ics" }

  get "confirmation/error", to: "public/confirm_records#error"
  get "confirmation/:confirm_action/:token", to: "public/confirm_records#confirm", as: :confirm_record_action
  delete "confirmation/destroy/:token", to: "public/confirm_records#destroy"

  use_doorkeeper do
    controllers applications: "oauth/applications"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get "user" => "users/status#show"

  authenticate :user do
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    match "/background" => BetterDelayedJobWeb, anchor: false, via: [:get, :post]
  end

  post "/graphql", to: "graphql#execute"

  get "/generate_204", to: "application#generate_204", status: 204

  get "*not_found", to: "application#not_found_404", status: 404

  root to: redirect("accounts")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_user_content.rb
# frozen_string_literal: true

class AppUserContent < ApplicationRecord
  validates_presence_of :content, :data_type, :data_source

  after_create :notify_admin

  private

    def notify_admin
      NotificationMailer.notify_admin(self).deliver_later
    end
end

# == Schema Information
#
# Table name: app_user_contents
#
#  id          :bigint           not null, primary key
#  content     :text(65535)
#  data_type   :string(255)
#  data_source :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/app_user_contents_controller.rb
# frozen_string_literal: true

class AppUserContentsController < ApplicationController
  layout "doorkeeper/admin"

  before_action :authenticate_user!
  before_action :authenticate_admin

  before_action :set_app_user_content, only: %i[show edit update destroy]

  def authenticate_admin
    render inline: "not allowed", status: 404 unless current_user.admin_role?
  end

  # GET /app_user_contents
  # GET /app_user_contents.json
  def index
    @app_user_contents = AppUserContent.all
  end

  # GET /app_user_contents/1
  # GET /app_user_contents/1.json
  def show
  end

  # GET /app_user_contents/new
  def new
    @app_user_content = AppUserContent.new
  end

  # GET /app_user_contents/1/edit
  def edit
  end

  # POST /app_user_contents
  # POST /app_user_contents.json
  def create
    @app_user_content = AppUserContent.new(app_user_content_params)

    respond_to do |format|
      if @app_user_content.save
        format.html do
          redirect_to @app_user_content,
                      notice: "App User Content was successfully created."
        end
        format.json { render :show, status: :created, location: @app_user_content }
      else
        format.html { render :new }
        format.json { render json: @app_user_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_user_contents/1
  # PATCH/PUT /app_user_contents/1.json
  def update
    respond_to do |format|
      if @app_user_content.update(app_user_content_params)
        format.html do
          redirect_to @app_user_content,
                      notice: "App User Content was successfully updated."
        end
        format.json { render :show, status: :ok, location: @app_user_content }
      else
        format.html { render :edit }
        format.json { render json: @app_user_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_user_contents/1
  # DELETE /app_user_contents/1.json
  def destroy
    @app_user_content.destroy
    respond_to do |format|
      format.html do
        redirect_to app_user_contents_url,
                    notice: "App User Content was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_app_user_content
      @app_user_content = AppUserContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_user_content_params
      params.require(:app_user_content).permit(:data_source, :data_type, :content)
    end
end

app/views/app_user_contents/_form.html.erb
<%= form_with(model: app_user_content, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <% if app_user_content.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(app_user_content.errors.count, "error") %> prohibited this app_user_content from being saved:
      </h2>

      <ul>
        <% app_user_content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :data_source %>
    <%= form.text_field :data_source, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :data_type %>
    <%= form.select :data_type, [["JSON", "json"]], {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <div id="code_editor" style="height: 400px;"></div>
  </div>

  <div class="form-group">
    <%= form.submit t("doorkeeper.applications.buttons.submit"), class: "btn btn-primary" %>
    <%= link_to t('doorkeeper.applications.buttons.cancel'), app_user_contents_path, class: "btn btn-default" %>
  </div>
<% end %>

<script>
  $(function () {
    var container = document.getElementById("code_editor")
    var options = {
      statusBar: false,
      modes: ['code', 'tree'],
      onChangeText: function(jsonString) {
        $("#app_user_content_content").val(jsonString);
      }
    }
    var editor = new JSONEditor(container, options)

    <% content = app_user_content.content.to_s.html_safe %>
    <% if content.present? %>
      editor.set(<%= content %>);
    <% else %>
      editor.set({});
    <% end %>
  });
</script>

app/views/app_user_contents/edit.html.erb
<div class="row">
  <div class="col">
    <h1>App User Content bearbeiten</h1>

    <%= render 'form', app_user_content: @app_user_content %>
  </div>
</div>

app/views/app_user_contents/index.html.erb
<div class="row">
  <div class="col">
    <h1>App User Contents</h1>

    <p><%= link_to 'New App User Content', new_app_user_content_path, class: "btn btn-success" %></p>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Source</th>
          <th>Type</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @app_user_contents.each do |app_user_content| %>
          <tr>
            <td class="align-middle"><%= link_to app_user_content.id, app_user_content_path(app_user_content) %></td>
            <td class="align-middle"><%= app_user_content.data_source %></td>
            <td class="align-middle"><%= app_user_content.data_type.upcase %></td>
            <td class="align-middle"><%= app_user_content.content %></td>
            <td class="align-middle" style="width: 70px"><%= link_to 'Destroy', app_user_content, method: :delete,class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/app_user_contents/new.html.erb
<div class="row">
  <div class="col">
    <h1>App User Content anlegen</h1>

    <%= render 'form', app_user_content: @app_user_content %>
  </div>
</div>

app/views/app_user_contents/show.html.erb
<div class="row">
  <div class="col">
    <h1>App User Content</h1>

    <div class="form-group">
      <label>Data source</label>
      <div><code><%= @app_user_content.data_source %></code></div>
    </div>

    <div class="form-group">
      <label>Data type</label>
      <div><code><%= @app_user_content.data_type %></code></div>
    </div>

    <div class="form-group">
      <label>Content</label>
      <div id="code_editor" style="height: 400px;"></div>
    </div>

    <div class="form-group">
      <%= link_to t('doorkeeper.applications.buttons.back'), app_user_contents_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

<script>
  $(function () {
    var container = document.getElementById("code_editor")
    var options = {
      statusBar: false,
      modes: ['code', 'view'],
      onEditable: function (node) {
        if (!node.path) {
          // In modes code and text, node is empty: no path, field, or value
          // returning false makes the text area read-only
          return false;
        }
      },
    }
    var editor = new JSONEditor(container, options)

    <% content = @app_user_content.content.to_s.html_safe %>
    <% if content.present? %>
      editor.set(<%= content %>);
    <% else %>
      editor.set({});
    <% end %>
  });
</script>