config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/health-check" => "health_check#show"

  namespace :notification do
    resources :wastes
    resources :devices do
      collection do
        delete "remove" => "devices#destroy"
        post "send_notifications" => "devices#send_notifications"
        post "send_notification/:id" => "devices#send_notification", as: :send_notification
      end
    end
    post "push_device_assignments/add" => "push_device_assignments#add", defaults: { format: "json" }
    delete "push_device_assignments/remove" => "push_device_assignments#remove", defaults: { format: "json" }
  end
  resources :categories
  resources :app_user_contents
  resources :static_contents
  resources :media_contents, only: %i[create], defaults: { format: "json" }
  get "data_provider", to: "data_provider#show", as: :data_provider
  get "data_provider/edit", as: :edit_data_provider
  post "data_provider/update", as: :update_data_provider
  resources :accounts do
    member do
      get "batch_defaults"
    end
  end

  get "/waste_calendar/export", to: "notification/wastes#ical_export", defaults: { format: "ics" }

  get "confirmation/error", to: "public/confirm_records#error"
  get "confirmation/:confirm_action/:token", to: "public/confirm_records#confirm", as: :confirm_record_action
  delete "confirmation/destroy/:token", to: "public/confirm_records#destroy"

  use_doorkeeper do
    controllers applications: "oauth/applications"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get "user" => "users/status#show"

  authenticate :user do
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
    match "/background" => BetterDelayedJobWeb, anchor: false, via: [:get, :post]
  end

  post "/graphql", to: "graphql#execute"

  get "/generate_204", to: "application#generate_204", status: 204

  get "*not_found", to: "application#not_found_404", status: 404

  root to: redirect("accounts")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

# Overide the Devise SessionController to enable login via json
# and return a json success message
class AccountsController < ApplicationController
  layout "doorkeeper/admin"

  before_action :authenticate_user!
  before_action :authenticate_admin

  include SortableController

  def authenticate_admin
    render inline: "not allowed", status: 404 unless current_user.admin_role?
  end

  def index
    @users = User
      .sorted_for_params(params)
      .where_email_contains(params[:query])
      .page(params[:page])
  end

  def edit
    @user = User.find(params["id"])
    @user.build_data_provider if @user.data_provider.blank?
    DataResourceSetting::DATA_RESOURCES.each do |data_resource|
      data_resource_settings = @user.data_provider.data_resource_settings.where(
        data_resource_type: data_resource.to_s
      )
      data_resource_settings.build if data_resource_settings.blank?
    end
  end

  def new
    @user = User.new
  end

  # POST /resource/sign_in
  def create
    @user = User.new(account_params)

    respond_to do |format|
      if @user.save
        @user.oauth_applications.create(
          name: "Zugriff per CMS",
          redirect_uri: "urn:ietf:wg:oauth:2.0:oob",
          confidential: true
        )
        flash[:notice] = "Nutzer wurde erstellt"
        format.html { redirect_to action: :edit, id: @user.id }
      else
        format.html { render action: :new }
      end
    end
  end

  # POST /resource/sign_in
  def update
    @user = User.find(params["id"])
    @user.update_attributes(account_params)
    flash[:notice] = "Nutzer aktualisiert"
    respond_to do |format|
      format.html { redirect_to action: :edit }
    end
  end

  # get /accounts/3/batch_defaults?data_resource_type=NewsItem
  def batch_defaults
    @user = User.find(params["id"])
    data_resource_type = params[:data_resource_type]
    system "rake batch_defaults:create DATAPROVIDER_ID=#{@user.data_provider_id} DATA_RESOURCE_TYPE=#{data_resource_type}"
    flash[:notice] = "Batch Action wurde gestartet für den Typ #{data_resource_type}"
    respond_to do |format|
      format.html { redirect_to action: :edit }
    end
  end

  def account_params
    values = params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :role,
      data_provider_attributes: [
        :id,
        :name,
        :data_type,
        :description,
        :notice,
        :role_point_of_interest,
        :role_tour,
        :role_news_item,
        :role_event_record,
        :role_push_notification,
        :role_lunch,
        :role_waste_calendar,
        :role_job,
        :role_offer,
        :role_construction_site,
        :role_survey,
        :role_encounter_support,
        :role_static_contents,
        :role_tour_stops,
        :role_deadlines,
        :role_noticeboard,
        :role_defect_report,
        logo_attributes: %i[
          id
          url
          description
        ],
        address_attributes: %i[
          id
          street
          addition
          zip
          city
        ],
        contact_attributes: %i[
          id
          first_name
          last_name
          phone
          fax
          email
        ],
        data_resource_settings_attributes: [
          :id,
          :data_resource_type,
          :display_only_summary,
          :always_recreate_on_import,
          :data_provider_id,
          :only_summary_link_text,
          :convert_media_urls_to_external_storage,
          :cleanup_old_records,
          :post_to_facebook,
          :facebook_page_id,
          :facebook_page_access_token,
          default_category_ids: []
        ]
      ]
    )
    values.delete_if { |_key, value| value.blank? }
  end

  def destroy
    @user = User.find(params["id"])
    @user.destroy
    flash[:notice] = "Nutzer wurde gelöscht"
    respond_to do |format|
      format.html { redirect_to action: :index }
    end
  end
end

app/views/accounts/edit.html.erb
<div class="row">
  <div class="col">
    <h1>Nutzer bearbeiten</h1>

    <%= form_for @user, url: account_path(@user), method: :patch, html: { class: 'form-horizontal', role: 'form' } do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col">
    <h1>Rollen</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Rolle</th>
          <th>Kommentar</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Admin</td>
          <td>
            Ein Administrator kann neue Inhalte erstellen, alle Inhalte lesen, bearbeiten und freigeben. <br />
            Neu erstellte Inhalte sind sofort freigegeben und damit öffentlich lesbar.
          </td>
        </tr>
        <tr>
          <td>App</td>
          <td>Ein mobile App kann alle freigegebene Inhalte lesen.</td>
        </tr>
        <tr>
          <td>User</td>
          <td>
            Ein User kann neue Inhalte erstellen und eigene Inhalte lesen und bearbeiten. <br />
            Neu erstellte Inhalte sind sofort freigegeben und damit öffentlich lesbar.
          </td>
        </tr>
        <tr>
          <td>Extended User</td>
          <td>
            Ein Extended User kann wie der User neue Inhalte erstellen und eigene Inhalte lesen und bearbeiten. <br />
            Neu erstellte Inhalte sind sofort freigegeben und damit öffentlich lesbar.
            Der Extended User kann zudem wie der Admin alle Inhalte lesen. Er kann jedoch nur eigene Inhalte bearbeiten.
          </td>
        </tr>
        <tr>
          <td>Restricted</td>
          <td>
            Ein beschränkter Account kann neue Inhalte erstellen und eigene Inhalte lesen und bearbeiten. <br />
            Neu erstellte Inhalte sind jedoch <strong>nicht</strong> freigegeben und können <strong>nicht</strong> von der Rolle 'App' gelesen werden.
          </td>
        </tr>
        <tr>
          <td>Editor</td>
          <td>
            Ein Editor kann neue Inhalte erstellen und eigene Inhalte lesen und bearbeiten. <br />
            Neu erstellte Inhalte sind sofort freigegeben und damit öffentlich lesbar. <br />
            Zudem kann er alle Inhalte von allen beschränkten Accounts lesen, bearbeiten und freigeben.
          </td>
        </tr>
        <tr>
          <td>Read only</td>
          <td>
            Ein "Read only" kann <strong>alle</strong> öffentlichen Inhalte nur lesen. <br />
            Dieser Account ist für externe Zugänge gedacht, bsp.: Veranstaltungsexporter
          </td>
        </tr>
      </tbody>
    </table>

    <h1 id="accounts">Nutzerverwaltung</h1>

    <p><%= link_to "Neuen Nutzer erstellen", new_account_path, class: "btn btn-success" %></p>

    <%= render partial: "search_form", locals: { form_path: accounts_path, search_column: "email" } %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th style="min-width: 55px">
            <%= link_to "ID", accounts_path(params_for_link(:id)) + "#accounts" %>
            <%= render partial: "sort_icon", locals: { sort_column: "id" } %>
          </th>
          <th>
            <%= link_to "E-Mail", accounts_path(params_for_link(:email)) + "#accounts" %>
            <%= render partial: "sort_icon", locals: { sort_column: "email" } %>
          </th>
          <th>Data Provider</th>
          <th>Rolle</th>
          <th>CMS POI <span class="badge badge-secondary">Kategorie gesetzt?</span></th>
          <th>CMS Tour <span class="badge badge-secondary">Kategorie gesetzt?</span></th>
          <th>CMS News Items <span class="badge badge-secondary">Kategorie gesetzt?</span></th>
          <th>CMS Event Records <span class="badge badge-secondary">Kategorie gesetzt?</span></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% data_provider = user.data_provider %>

          <tr id="user_<%= user.id %>">
            <td class="align-middle"><%= user.id %></td>
            <td class="align-middle"><%= link_to user.email, edit_account_path(user) %></td>
            <td class="align-middle"><%= data_provider.try(:name) %></td>
            <td class="align-middle"><%= user.role.try(:humanize) %></td>
            <td class="align-middle">
              <span class="badge <%= data_provider.try(:role_point_of_interest) ? 'badge-success' : 'badge-danger' %>">
                <%= data_provider.try(:role_point_of_interest) ? "aktiv" : "" %>
              </span>
                <% if data_provider.try(:settings, "PointOfInterest")&.has_default_categories? %>
                  <span class="badge badge-secondary">ja</span>
                <% end %>
            </td>
            <td class="align-middle">
              <span class="badge <%= data_provider.try(:role_tour) ? 'badge-success' : 'badge-danger' %>">
                <%= data_provider.try(:role_tour) ? "aktiv" : "" %>
              </span>
              <% if data_provider.try(:settings, "Tour")&.has_default_categories? %>
                <span class="badge badge-secondary">ja</span>
              <% end %>
            </td>
            <td class="align-middle">
              <span class="badge <%= data_provider.try(:role_news_item) ? 'badge-success' : 'badge-danger' %>">
                <%= data_provider.try(:role_news_item) ? "aktiv" : "" %>
              </span>
              <% if data_provider.try(:settings, "NewsItem")&.has_default_categories? %>
                <span class="badge badge-secondary">ja</span>
              <% end %>
            </td>
            <td class="align-middle">
              <span class="badge <%= data_provider.try(:role_event_record) ? 'badge-success' : 'badge-danger' %>">
                <%= data_provider.try(:role_event_record) ? "aktiv" : "" %>
              </span>
              <% if data_provider.try(:settings, "EventRecord")&.has_default_categories? %>
                <span class="badge badge-secondary">ja</span>
              <% end %>
            </td>
            <td class="align-middle" style="width: 70px">
              <%= link_to t('doorkeeper.applications.buttons.edit'), edit_account_path(user), class: "btn btn-sm btn-outline-secondary" %>
            </td>
            <td class="align-middle" style="width: 70px">
              <%= link_to "Destroy", account_path(user), method: :delete, class: "btn btn-sm btn-outline-danger", data: { confirm: "Sind sie sicher?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @users, theme: "twitter-bootstrap-4" %>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="row">
  <div class="col">
    <h1>Nutzer anlegen</h1>

    <%= form_for @user, url: accounts_path, method: :post, html: { class: 'form-horizontal', role: 'form'} do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
    <% end %>
  </div>
</div>